CREATE TABLE tblRoleLogs (
	RoleLogId INT IDENTITY(1,1),
	RoleName NVARCHAR(100),
	UpdatedDate DATE DEFAULT CAST(GETDATE() AS DATE),
	UpdatedBy INT
	CONSTRAINT PK_tblRoleLogs PRIMARY KEY (RoleLogId)
)
go

CREATE TABLE tblUserLogs(
	UserLogId INT IDENTITY(1,1),
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100),
	[Role] INT,
	EmailId NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
	PhoneNumber BIGINT,
	Photo NVARCHAR(MAX),
	BirthDate DATE,
	[Address] NVARCHAR(MAX) NOT NULL,
	City INT,
	JoiningDate DATETIME2 NOT NULL DEFAULT CAST(GETDATE() AS Date),
	CreatedAt DATE NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	UpdatedDate DATE DEFAULT CAST(GETDATE() AS DATE),
	UpdatedBy INT
	CONSTRAINT PK_tblUserLogs PRIMARY KEY (UserLogId),
	CONSTRAINT FK_tblUserLogs_tblRoles FOREIGN KEY ([Role]) REFERENCES tblRoles(RoleId),
	CONSTRAINT FK_tblUserLogs_tblCities FOREIGN KEY (City) REFERENCES tblCities(CityId),
)